modLoader = "javafml"
loaderVersion = "[${forge_version},)"
issueTrackerURL = "https://github.com/Cannoneers-of-Create/CreateBigCannons/issues"
license = "MIT"

[[mods]]
modId = "createbigcannons"
version = "${version}"
displayName = "Create Big Cannons"
authors = "rbasamoyai"
description = '''Artillery engineering comes to Create'''
logoFile = "icon.png"

[[dependencies.createbigcannons]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.createbigcannons]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.createbigcannons]]
modId="create"
mandatory=true
versionRange="${create_version}"
ordering="NONE"
side="BOTH"